version: 2.1
defaults: &defaults
  environment:
    IMAGE_NAME: tensorflow-retrained-supermarket
    IMAGE_TAG: latest
    DOCKERFILE: Dockerfile-retrain

docker-releasable: &docker-releasable
  filters:
    branches:
      only:
        - docker
only-releasable: &only-releasable
  filters:
    branches:
      only:
        - master
        - develop
        - patch
non-releasable: &non-releasable
  filters:
    branches:
      ignore:
        - master
        - develop
        - patch
        - docker
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Login
          command: |
            #echo $DOCKER_USER_PASSWORD | base64 --decode | docker login -u $DOCKER_USER_NAME --password-stdin
            docker login -u $DOCKER_USER_NAME -p $DOCKER_USER_PASSWORD
      - run:
          name: Docker Build
          command: |
            echo $GOOGLE_APPLICATION_CREDENTIALS > ./account.json
            docker build -t $IMAGE_NAME:$IMAGE_TAG -f $DOCKERFILE .
            docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKER_USER_NAME/$IMAGE_NAME:$IMAGE_TAG
            docker push $DOCKER_USER_NAME/$IMAGE_NAME:$IMAGE_TAG
  test:
    <<: *defaults
    docker:
      - image: $DOCKER_USER_NAME/$IMAGE_NAME:$IMAGE_TAG
    steps:
      - checkout
      - run:
          name: Perform one time test
          command: |
            ls
workflows:
  version: 2.1  
  tensorflow_workflow:
    jobs:
      - build:
        <<: *docker-releasable
      - test:
        <<: *docker-releasable
        requires:
          build
        