version: 2.1
defaults: &defaults
  environment:
    IMAGE_NAME: tensorflow-retrained-supermarket
    IMAGE_TAG: $CIRCLE_BUILD_NUM
    DOCKERFILE: Dockerfile-retrain

docker-releasable: &docker-releasable
  filters:
    branches:
      only:
        - docker
only-releasable: &only-releasable
  filters:
    branches:
      only:
        - master
        - develop
        - patch
non-releasable: &non-releasable
  filters:
    branches:
      ignore:
        - master
        - develop
        - patch
        - docker
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Login
          command: |
            docker login -u $DOCKER_USER_NAME -p $DOCKER_USER_PASSWORD
      - run:
          name: Prepare
          command: |
            echo $GOOGLE_APPLICATION_CREDENTIALS > /tmp/account.json
      - run:
          name: Docker Build
          command: |
            docker build -t $IMAGE_NAME:$IMAGE_TAG -f $DOCKERFILE .

workflows:
  version: 2.1  
  tensorflow_workflow:
    jobs:
      - build:
        <<: *docker-releasable