version: 2.1
defaults: &defaults
  environment:
    IMAGE_NAME: tensorflow-retrained-experience
    IMAGE_TAG: latest
    DOCKERFILE: Dockerfile
    SCRIPTS_DIRECTORY: /home/tensorflowEx/scripts

docker-releasable: &docker-releasable
  filters:
    branches:
      only:
        - dockerhub-ci
only-releasable: &only-releasable
  filters:
    branches:
      only:
        - master
        - develop
        - patch
non-releasable: &non-releasable
  filters:
    branches:
      ignore:
        - master
        - develop
        - patch
        - dockerhub-ci
jobs:
  build-image:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Login
          command: |
            docker login -u $DOCKER_USER_NAME -p $DOCKER_USER_PASSWORD
      - run:
          name: Docker Build
          command: |
            echo $GOOGLE_APPLICATION_CREDENTIALS > ./account.json
            docker build -t $IMAGE_NAME:$IMAGE_TAG -f $DOCKERFILE .
            docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKER_USER_NAME/$IMAGE_NAME:$IMAGE_TAG
            docker push $DOCKER_USER_NAME/$IMAGE_NAME:$IMAGE_TAG
            rm -vfr ./account.json
      - run:
          name: Docker Push
          command: |
            docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKER_USER_NAME/$IMAGE_NAME:$IMAGE_TAG
            docker push $DOCKER_USER_NAME/$IMAGE_NAME:$IMAGE_TAG
      - run:
          name: Test
          command: |
            docker run --rm -i -w $SCRIPTS_DIRECTORY $DOCKER_USER_NAME/$IMAGE_NAME:$IMAGE_TAG python label.py $SCRIPTS_DIRECTORY/maionese.jpg
            
workflows:
  version: 2.1
  tensorflow_workflow:
    jobs:
      - build-image:
          <<: *docker-releasable
        
