version: 2.1
defaults: &defaults
  environment:
    IMAGE_NAME: tensorflow-retrained-experience
    IMAGE_TAG: latest
    DOCKERFILE: Dockerfile
    DOCKER_SCRIPTS_DIRECTORY: /home/tensorflowEx/scripts
    TERRAFORM_FOLDER: ./Terraform

terraform-releasable: &terraform-releasable
  filters:
    branches:
      only:
        - terraform
docker-releasable: &docker-releasable
  filters:
    branches:
      only:
        - docker
only-releasable: &only-releasable
  filters:
    branches:
      only:
        - master
        - develop
        - patch
non-releasable: &non-releasable
  filters:
    branches:
      ignore:
        - master
        - develop
        - patch
        - docker
        - terraform

working_directory: &working_directory
  ~/example

repo_cache_key: &repo_cache_key
  v1-repo-{{ .Branch }}-{{ .Revision }}

restore_repo: &restore_repo
  restore_cache:
    key: *repo_cache_key

save_repo: &save_repo
  save_cache:
    key: *repo_cache_key
    paths:
      - *working_directory
      
terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      cd $TERRAFORM_FOLDER
      terraform init
      
apply_job: &apply_job
  <<: *defaults
  steps:
    - *restore_repo
    - *terraform_init
    - attach_workspace:
        at: *working_directory
    - run:
        name: terraform apply
        command: |
          cd $TERRAFORM_FOLDER
          terraform apply --auto-approve ../terraform.plan      
jobs:
  develop-pipeline:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Unit Test
          command: |
            docker run --rm -i -w $DOCKER_SCRIPTS_DIRECTORY $DOCKER_USER_NAME/$IMAGE_NAME:$IMAGE_TAG python label.py $DOCKER_SCRIPTS_DIRECTORY/maionese.jpg
  docker-pipeline:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Login
          command: |
            docker login -u $DOCKER_USER_NAME -p $DOCKER_USER_PASSWORD
      - run:
          name: Docker Build
          command: |
            echo $GOOGLE_APPLICATION_CREDENTIALS > ./account.json
            docker build -t $IMAGE_NAME:$IMAGE_TAG -f $DOCKERFILE .
            rm -vfr ./account.json
      - run:
          name: Docker Push
          command: |
            docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKER_USER_NAME/$IMAGE_NAME:$IMAGE_TAG
            docker push $DOCKER_USER_NAME/$IMAGE_NAME:$IMAGE_TAG
      - run:
          name: Docker Run Test
          command: |
            docker run --rm -i -w $DOCKER_SCRIPTS_DIRECTORY $DOCKER_USER_NAME/$IMAGE_NAME:$IMAGE_TAG python label.py $DOCKER_SCRIPTS_DIRECTORY/maionese.jpg
  
  plan:
    <<: *defaults
    steps:
      - *restore_repo
      - *terraform_init
      - run:
          name: terraform plan
          command: |
            cd $TERRAFORM_FOLDER
            terraform plan -out=../terraform.plan
      - persist_to_workspace:
          root: *working_directory
          paths:
            - ../terraform.plan
  apply:
    <<: *apply_job
    
workflows:
  version: 2.1
  tensorflow_workflow:
    jobs:
      - develop-pipeline:
          <<: *only-releasable
      - docker-pipeline:
          <<: *docker-releasable
      - plan:
          <<: *non-releasable
      - apply:
          <<: *non-releasable
          requires:
            - plan
