version: 2.1
defaults: &defaults
  environment:
    PROJECT_TEST: /home
    JS_SCRIPT_PATH: _scripts
    DELIVERED_APP_PATH: place_holder
    GITHUB_EMAIL: rodolfotiago@gmail.com
    GITHUB_USER_NAME: rodolfotiago
    DEV_KOBITON_USER: place_holder
    DEV_KOBITON_API: place_holder
    INCREMENT_VERSION_SCRIPT: place_holder

docker-releasable: &docker-releasable
  filters:
    branches:
      only:
        - docker
only-releasable: &only-releasable
  filters:
    branches:
      only:
        - master
        - develop
        - patch
non-releasable: &non-releasable
  filters:
    branches:
      ignore:
        - master
        - develop
        - patch
        - docker
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/buildpack-deps:xenial
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Build
          command: echo ok

workflows:
  version: 2.1
  
  tensorflow_workflow:
    jobs:
      - build:
        <<: *docker-releasable
